### ISSUE TITLE
Design considerations

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/offscreen_render#1]
How should this utility be designed?

_API requirements:_
- Given an OpenRAVE Kinbody, render its visual or collision mesh offscreen
- Rendering should be done from the perspective of a calibrated camera in the scene.
- Extract depth buffer and/or point cloud
- Extract occlusion and labels of per-pixel object labels

_Challenges:_
- Rendering in OpenRAVE is totally seperate from environment representation via the Viewer plugin.
- Visual meshes have to be loaded from files. They are not represented directly in OpenRAVE.
- Interfacing with OpenRAVE primarily done through python. 
- Camera intrinsics are stored in ROS, not in OpenRAVE
- Output of the system needs to be intensively processed and compared against point clouds, which again, come through ROS.
- Who owns the OpenGL context? OpenGL will complain if not run in the main thread. Many OpenGL windowing utilities have blocking semantics when opening and updating a context. GLUT, for instance, has a function `glutMainLoop` that blocks until the application is finished.
- How do we communicate which objects should be rendered, and at what transforms?

**Possibilities:**

**ROS Node**
This could be done by shipping mesh markers over ROS to a C++ node. The node reads camera intrinsics from ROS, opens an OpenGL context in-process, renders the images, and then sends them back via ROS.

**RVIZ Plugin**
Renders objects via RVIZ, like `or_rviz`, otherwise has the same behavior as "ROS Node". Would require RVIZ to be running with special settings.

**C++ OpenRAVE Plugin**
A plugin of some kind is written which opens an OpenGL context, renders OpenRAVE kinbodies, and ships back images either in-process or through ROS. Camera intrinsics and pose still need to come through ROS. Communication is through plugin interface. Plugin has to be responsible for loading .dae/.stl files from visual geometry.

**Python Script**
Python inlines opengl/GLUT and uses it to render the images. User directlyy calls python functions. Somewhat challenging to make this performant and interface with PCL. Script has to be responsible for loading .dae/.stl files.

**Comment by mklingen** [comment]
heh, turned out to be ridiculously easy to render a depth buffer image in python ![depth buffer image](http://i.imgur.com/o9Nl93n.png)

Now to figure out how to get OpenRAVE models + camera intrinsics

**Comment by mklingen** [comment]
It looks like the best way to do this is to
- API will be two things: a list of kinbodies, and a description of a camera.
- Create a python offscreen rendering utility that initializes an openGL context by creating a tiny offscreen window
- It then renders all of the requested kinbodies. Produces a framebuffer object: one for depth and one for color. Framebuffers get converted into OpenCV python images and/or numpy arrays.
- After rendering a single frame, closes the glut window and returns control to the caller.
- Images can then be published to ROS and/or processed in python
- Important that the utility gets called from the main thread.

**Comment by mklingen** [comment]
Ah, the old OpenRAVE rendering design:
1. Every kinbody has many links
2. Every link has many geometries
3. A geometry has "Collision data" and a "Render Mesh"
4. The "Render Mesh" is an arbitrary file name. May be `.dae`, `.stl`, `.iv` or anything else
5. Colors can be in the render mesh, but every geometry also has a "diffuse color"

So right now I'm just going to render collision meshes until I find a good solution for importing render meshes

**Comment by mklingen** [comment]
sort of working now:

![image](http://i.imgur.com/Lq8ZI0j.png)

**Comment by psigen** [comment]
What are the library dependencies we are adding in for this?

Looks good, btw.

**Comment by mklingen** [comment]
OpenGLPy + Gloo. These have their own dependencies : numpy (already have), vispy, and panda. They were not too difficult to install. 

Also requires install of GLUT

**Comment by mklingen** [comment]
This is what the color index i'm rendering looks like (useful for occlusion queries) ![image](http://i.imgur.com/zp4ECqk.png)

**Comment by mklingen** [comment]
Making some progress. Right now the major issue is that camera poses/intrinsics are only stored in ROS right now, and only work when the robot is on, so its hard to test in simulation. Also there is the annoying fact that TF data is not published anywhere in simulation. Going to try to fake some of it by plugging in a kinect on my machine and using its pose/intrinsics as a reference instead.

**Comment by mklingen** [comment]
Now I can render an OpenRAVE scene from the perspective of any ROS camera:

![image](http://i.imgur.com/Zix6YEz.png)

Only supports rendering the collision model right now, but I can select arbitrary collections of objects to render. It's pretty fast too, runs at 100s of frames per second.

**Comment by cdellin** [comment]
Haha nice going Matt.  Also, that rendered depth image is absolutely terrifying ...

**Comment by mklingen** [comment]
Yeti herb

**Comment by mklingen** [comment]
autogenerated herb index buffer ![image](http://i.imgur.com/gs1iGjr.png)

**Comment by mklingen** [comment]
Now with offscreen rendering and export to opencv/matplotlib

![image](http://i.imgur.com/ocel4jL.png)

Due to limitation in rendering pipeline, it can't currently represent depths greater than 1 meter. I suppose I will have to just settle for normalized coordinates, and do the multiplication by the near/far plane outside of the shader when producing synthetic point clouds instead.

**Comment by mklingen** [comment]
And now, the whole reason I was doing this: synthetic point cloud.

![image](http://i.imgur.com/LcG1Tl6.png)

There are a few issues. I am not sure whether the collision models are just off from the visual models, or if there is a bug in my point projection code. The range of the representable depth is also very small (0 to 1 meter), and the points have depth aliasing at a resolution of 1/256 of a meter. Without hardware acceleration, the point cloud takes about 5 seconds to produce for an image the size of the Kinect. I will have to come up with a way to reproject the points using the GPU instead to make it fast.

Aside from that, I am very close to being able to do arm/object tracking now.

**Comment by cdellin** [comment]
That's so awesome Matt!  I can't wait for Herb arm tracking, especially.

**Comment by mklingen** [comment]
Can now simulate the full range of the depth camera without much aliasing (32 bit instead of 8 bit depth) ![image](http://i.imgur.com/9e9EV4i.png)

Point cloud generation still too slow for my tastes. I think I will write a shader to do this for me. There is also still a small offset in the cloud. Might be a bug in setting up the opengl view matrix.

**Comment by mkoval** [comment]
Why is there an offset between the point cloud and the rendered model? It
looks like the entire model is shifted "down and to the right" (from the
perspective of the camera).

**Comment by mklingen** [comment]
Used a shader and got the point creation time down from 2 seconds to around 0.5 seconds. Bottleneck is now creating a ROS message. Declaring that time good enough. Now I will implement an actual ICP app.

EDIT: @mkoval  yes, I see that. Not sure why. I think I am just using the wrong reference frame for the camera view matrix.

**Comment by mklingen** [comment]
Okay, I've run into a snag. Now all that's left is to align the synth point clouds with sensor data. I was hoping to do this in python using `python-pcl`, but I cannot get `python-pcl` to compile in our system because it depends on a PCL version that is higher than the one found in ros hydro, as well as `cython`. I'm not sure if its worth it to pull in `python-pcl` just to do ICP.

There is also the issue of interfacing with ROS. The point cloud interface to ROS in python is pretty horrible. It's just an array of structs with named "X, Y, Z" fields. Converting to and from ROS messages and numpy arrays takes many seconds. `python-pcl` is not integrated with ROS at all.
