### ISSUE TITLE
Add API interfaces for python use.

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/offscreen_render#2]
By request of @siddhss5  and Rachel. Need to add an interface to directly access images produced by `offscreen_render` from python. Right now my plan is to make a string interface for adding objects to be rendered, and either a `OpenRAVE::Sensor` interface or a raw string interface for getting the data back.

**Comment by mklingen** [comment]
I've started implementing a basic `SensorBase` class that spits out rendered images, but I'm a little confused as to how openrave sensors are actually added to the environment and configured. As far as I can tell, the only way to do this is to add it to the robot's xml file, and even then it looks like only the standard sensor types are supported? :/ maybe @mkoval knows how?

**Comment by mklingen** [comment]
I see, I need to follow the example of [BaseCamera](http://robotics.naist.jp/~akihiko-y/doxy/openrave2011-08-04/basecamera_8h_source.html) and add the typical openrave string commands for configuring the camera.

**Comment by mkoval** [comment]
You can programmatically create a sensor using `openravepy.RaveCreateSensor` (this is the same as we do for planners and viewers). You attach it to the robot using `robot.AddAttachedSensor`, which takes an `AttachedSensorInfo` struct.

I'm not sure how to populate this struct in Python. You may have to do it using XML (like you suggest). Or we may have to add the appropriate methods to OpenRAVE's Python bindings. Obscure features like this are often missing from the Python API.

**Comment by mklingen** [comment]
@mkoval do you know if `prpy` runs in the main thread? Like, when I do ipython embed, and then send a command, is that command run in the main thread (if that makes sense)?

**Comment by mklingen** [comment]
Alright, check out these occlusions! Haven't quite got it outputting to python yet but I'm nearly there.

![](http://i.imgur.com/OOttPpV.png)

![](http://i.imgur.com/cc79mGq.png)

**Comment by mklingen** [comment]
aw yeah, directly accessible in numpy now (here's a pyplot image)

![](http://i.imgur.com/zaVev5J.png)

And, if you make all of the desired object black, you can count the number of pixels just by going:

``` python
numpy.count_nonzero(data.imagedata)

Out[21]: 13983
```

Otherwise, you've got to check the R, G, B channels for the desired color (user sets the color of each object using the python interface)

**Comment by mklingen** [comment]
This is how the interface looks right now (very verbose!)

``` python
# Load some objects and set them up in the environment
env.Load('/home/mklingen/prdev/src/pr-ordata/data/objects/bowl.kinbody.xml')
env.Load('/home/mklingen/prdev/src/pr-ordata/data/objects/fuze_bottle.kinbody.xml')
bowl = env.GetKinBody('bowl')
fuze = env.GetKinBody('fuze_bottle')
tf = fuze.GetTransform()
tf[0:3, 3] = numpy.array([0, 0, 1])
fuze.SetTransform(tf)

# Create the sensor
sensor = openravepy.RaveCreateSensor(env, 'offscreen_render_camera')
# Set its intrinsics (fx, fy, cx, cy, near, far)
sensor.SendCommand('setintrinsic 529 525 328 267 0.01 10')
# And its resolution in pixels
sensor.SendCommand('setdims 640 480')
#Initialize the sensor. Right now the size of the sensor can't be changed after you do this.
# It will also open up an annoying opengl window just to get context.
sensor.Configure(openravepy.Sensor.ConfigureCommand.PowerOn)
# Add bodies to render with the given (r, g, b) colors
sensor.SendCommand('addbody bowl 255 0 0')
sensor.SendCommand('addbody fuze_bottle 0 255 0')
# You can also set the sensor's extrinsic transform
sensor.SetTransform([...])
# This is how you make it render a frame (the argument is meaningless)
sensor.SimulationStep(0.01)

# Copy data from OpenGL using the sensor interface
data = sensor.GetSensorData();

# This is now a W x H x 3 numpy array filled with bytes
img = data.imagedata

#You can plot the data if you want
matplotlib.pyplot.imshow(img)

```
